### ISSUE TITLE
sample data Product Image not show in frontend and adminpanel

### ISSUE THREAD

**Issue by sunflower-tc** [markshust/docker-magento#1052]
**Description**
bin/magento sampledata:deploy && bin/magento setup:upgrade

**Steps To Reproduce**
Product images are not displayed in the front-end and back-end administration, there is no media/catalog/product folder
![image](https://github.com/markshust/docker-magento/assets/15952571/4ab13b6d-57c5-454e-838d-971798bf3a90)

**Expected Result**
Front and back-end product images are displayed properly

**Actual Result**

**Comment by YevhenZvieriev** [comment]
Hi, @sunflower-tc 

You can solve this follow:

```
rm -rf pub/media/catalog/product/cache/*
```
```
bin/magento catalog:images:resize
```
```
bin/magento setup:static-content:deploy
```
```
bin/magento setup:upgrade
```

**Comment by markshust** [comment]
I'm unable to replicate this issue.

Note that running:

```
bin/magento sampledata:deploy && bin/magento setup:upgrade
```

Is different from running:
```
bin/magento sampledata:deploy
bin/magento setup:upgrade
```

This is because the local bin/magento script which pipes commands through the container is different from the bin/magento script within the container. I'd recommend running both lines separately and see if it fixes this. But since I'm unable to replicate this on a new install, I'll be closing this ticket out.
