### ISSUE TITLE
Remove obsolete version directive from docker compose files

### ISSUE THREAD

**Issue by o0mohd0o** [markshust/docker-magento#1135]
**Description**

This issue happens start with version 25.05 of docker

WARN[0000] /Users/mohd/Sites/magento2/compose.yaml: `version` is obsolete 
WARN[0000] /Users/mohd/Sites/magento2/compose.healthcheck.yaml: `version` is obsolete 
WARN[0000] /Users/mohd/Sites/magento2/compose.dev.yaml: `version` is obsolete 

Please check the solution here:
https://github.com/mailcow/mailcow-dockerized/issues/5797#issuecomment-2011349228

**Steps To Reproduce**
1. bin/start

**Expected Result**
No any warn should appear

**Actual Result**

**Comment by YevhenZvieriev** [comment]
Hi @o0mohd0o 

This issue was fixed in this [PR](https://github.com/markshust/docker-magento/pull/1125).

For hot-fix, until changes won't merge from the `release/next` branch to `master` you can remove `version: "3"` from docker files that throw warnings such as `compose.yaml`, `compose.healthcheck.yaml`, `compose.dev.yaml`.

**Comment by markshust** [comment]
Closing this one out as it was fixed in https://github.com/markshust/docker-magento/pull/1125. I'll be building and tagging a new release momentarily.
