### ISSUE TITLE
Could not find package magento/project-4-edition with version 2

### ISSUE THREAD

**Issue by KexingWestRoad** [markshust/docker-magento#1217]
Composer auth has already been set up.
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Creating a "magento/project-4-edition=2" project at "./"

In CreateProjectCommand.php line 424:

  Could not find package magento/project-4-edition with version 2.

**Comment by aveshnaik007** [comment]
Same here

**Comment by aveshnaik007** [comment]
@KexingWestRoad The issue which I faced was the last character was not copied from the documentation curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento.test 2.4.7 communit
The "communit" was the issue here it should been "community". This solved my above problem.
