### ISSUE TITLE
Question: Where is Extension Manager ?

### ISSUE THREAD

**Issue by protzi** [markshust/docker-magento#124]
I would like to use Extension Manager, but there is no such functionality in admin panel....
How to enable it?
https://devdocs.magento.com/guides/v2.3/comp-mgr/extens-man/extensman-main-pg.html
<img width="633" alt="screen shot 2019-02-05 at 4 39 11 pm" src="https://user-images.githubusercontent.com/17887536/52280601-ee1f2e00-2964-11e9-8947-3ff92dad5f4a.png">

**Comment by markshust** [comment]
That's a good question

Leaving this link for reference https://devdocs.magento.com/guides/v2.3/comp-mgr/extens-man/extensman-checklist.html

**Comment by markshust** [comment]
I don't believe we can use extension manager, as this image appeared since I last looked at the above link:

![Screen Shot 2019-12-21 at 9 06 36 AM](https://user-images.githubusercontent.com/437029/71309034-360a4080-23d1-11ea-94f3-848942e9cbd8.png)

I'm not sure any developer will ever use Extension Manager anyways, the recommended way to deal with anything like this is with command line. I'll be closing this out as wontfix.
