### ISSUE TITLE
 ✘ elasticsearch Error manifest for markoshust/magento-elasticsearch:7 not found: manifest unknown: manifest unknown 

### ISSUE THREAD

**Issue by asma-hawari-cko** [markshust/docker-magento#1241]
**Description**

i want to install magento 2.4.5 so i want to use ealsticsearch
**Steps To Reproduce**
1. bin/install

**Expected Result**
installed successfully

**Actual Result**
error in the creation of the docker image, could you please confirm that i am using the correct one ? image: markoshust/magento-elasticsearch:8.13-0 this is also creating problems and it's not working with the magento 2.4.5 and php 8.1x 
WARNING: COMPAT locale provider will be removed in a future release
{"@timestamp":"2024-11-08T12:13:09.613Z", "log.level": "INFO", "message":"Using [jdk] native provider and native methods for [Linux]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.nativeaccess.NativeAccess","elasticsearch.node.name":"7858c9ff27b0","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-11-08T12:13:09.850Z", "log.level": "INFO", "message":"Java vector incubator API enabled; uses preferredBitSize=128; FMA enabled", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.apache.lucene.internal.vectorization.PanamaVectorizationProvider","elasticsearch.node.name":"7858c9ff27b0","elasticsearch.cluster.name":"docker-cluster"}

**Comment by YevhenZvieriev** [comment]
Hi, @asma-hawari-cko 

Magento 2.4.5 and PHP 8.1 generally require Elasticsearch 7.x rather than 8.x. The `markoshust/magento-elasticsearch:8.13-0` image might cause compatibility issues since Magento 2.4.5 does not officially support Elasticsearch 8.x out of the box.

I suggest switching to an Elasticsearch 7.x image, such as `markoshust/magento-elasticsearch:7.17`, to align with Magento’s supported versions. This change should be compatible with Magento 2.4.5 and PHP 8.1, and it might resolve the errors you're encountering.

Additionally, feel free to run the `bin/check-dependencies` script, which I specifically developed to verify that all dependencies align correctly. This should help ensure compatibility and prevent further issues :)

**Comment by markshust** [comment]
Magento 2.4.5 is now two versions behind, and I only support the most recent (2.4.7) and one-version behind (2.4.5), otherwise this turns into a full-time job for me to support legacy software, something I'm not at all interested in doing. Feel free to fork & pull!
