### ISSUE TITLE
Implement Varnish

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#127]

**Comment by wigman** [comment]
Been kinda busy. but it's on it's way.

**Comment by markshust** [comment]
awesome! no worries

**Comment by wigman** [comment]
I’m as good as ready. Will PR tomorrow.
What’s your preferred method to push the images to the docker-cloud?
Just PR everything under your namespace and you push compile and push them locally?
Think I’d prefer that over me pushing to your docker account. What do you think?

**Comment by wigman** [comment]
You can check current state here: https://github.com/wigman/docker-magento

**Comment by markshust** [comment]
just a PR into this repo would be good. i will pull down locally and test. if all good, i'll trigger a rebuild of images and it should be good to go. don't worry about tagging/versioning/etc, i'll take care of that. fyi i'll be away from my computer for a few days but can probably take a look at all this after the weekend.

**Comment by wigman** [comment]
So, having worked with the Varnish version for a while now, I'm not sure if you want Varnish _on_ by default.
An annoying thing while developing, for example, is that the varnish VCL by default caches static and media folders. So whenever changing js files, you need to flush varnish.

I'm currently working locally with a vcl that skips caching of /static/ files, like this:
```    # For development, disable caching of static content
    if (req.url ~ "^/(pub/)?(static)/.*\.(ico|css|js|jpg|jpeg|png|gif|tiff|bmp|mp3|ogg|svg|swf|woff|woff2|eot|ttf|otf)$") {
        return (pass);
    }```

I'd say it's super useful when you need to build/test things on Varnish, but it's not helpful in development.

Maybe we should offer 2 compose files to choose from, or have the proxy setup in a way so that you can skip varnish in requests?

I think there's room for discussion here. Have you tried my branch yet?

**Comment by markshust** [comment]
sorry i was knee-deep in the releasing the course related to this repo. i'll get a chance to look at this over the next couple days. we definitely want varnish off by default (treat it like xdebug usage).

perhaps a flag to start with varnish? `bin/start --with-varnish`

**Comment by freeyland** [comment]
Any update on this one?

**Comment by wigman** [comment]
We moved on from this approach to a setup with a proxy that can toggle to either varnish or directly to phpfpm.
This way, phpfpm container is not recreated when changing the docket config (which would otherwise wipe out the data I side the container).
Not planning to build this into this repo.

You probably don’t want to have varnish always enabled, since it really hinders your dev-workflow.

**Comment by markshust** [comment]
I'm closing this out, I don't think there is any demand here for Varnish support in this repo.

**Comment by joshdavenport** [comment]
@wigman assuming this proxy was effectively totally separate to the environment managed by this repo right? Do you have any advice around setting this up?

We have a need to do some testing/debugging with varnish in use. Generally totally agree that there's no demand to have it as a permanent part of this repo. Lack of activity in this ticket certainly demonstrates this!

That being said, with this repo having the success and usage that it does I think there's certainly value in providing a bit of advice of how one might go about using it to complement what's here, but certainly not supported as a first class citizen.
