### ISSUE TITLE
pread() "/var/www/html/nginx.conf" failed (21: Is a directory)

### ISSUE THREAD

**Issue by acampos1916** [markshust/docker-magento#156]
Not sure if this a proper issue but I'm trying to use this Docker setup to work on a Magento Cloud project. The app container exits after being launched.

> 2019/06/11 12:41:17 [crit] 1#1: pread() "/var/www/html/nginx.conf" failed (21: Is a directory) nginx: [crit] pread() "/var/www/html/nginx.conf" failed (21: Is a directory)

The project has no nginx.conf file in src/, I tried creating a dummy one but still no success. Is this Docker setup supposed to work with Cloud as well as regular Magento projects?

**Comment by markshust** [comment]
yes, magento cloud projects are still just magento source code. i am currently using this setup on a magento cloud project.

i'm not sure what happened here, but perhaps try deleting the file?

`bin/cli rm nginx.conf`

then

`bin/stop`

then, copy the nginx.conf file over to your root, then start the containers back up with:

`bin/start`

let me know if that works for you.

**Comment by wbfiretoss** [comment]
Same problem here. 

warren@asus:~/Sites/oliveandcocoa$ docker logs f25fe
2019/12/10 22:15:30 [crit] 1#1: pread() "/var/www/html/nginx.conf" failed (21: Is a directory)
nginx: [crit] pread() "/var/www/html/nginx.conf" failed (21: Is a directory)
2019/12/10 22:58:16 [crit] 1#1: pread() "/var/www/html/nginx.conf" failed (21: Is a directory)
nginx: [crit] pread() "/var/www/html/nginx.conf" failed (21: Is a directory)
2019/12/10 22:59:17 [crit] 1#1: pread() "/var/www/html/nginx.conf" failed (21: Is a directory)
nginx: [crit] pread() "/var/www/html/nginx.conf" failed (21: Is a directory)
warren@asus:~/Sites/oliveandcocoa$ bin/cli rm nginx.conf
rm: cannot remove 'nginx.conf': Is a directory



warren@asus:~/Sites/oliveandcocoa$ bin/cli rm nginx.conf
rm: cannot remove 'nginx.conf': Is a directory

**Comment by Krielkip** [comment]
nginx.conf in the container is an symlink from nginx.conf.sample. 
Which is automatic copied while setup from Magento Vendor folder.
The problem is, that the copy doesn't make the file, but as an folder (nginx.conf.sample)

Solution:

make file in src root: nginx.conf.sample
```
## Example configuration:
# upstream fastcgi_backend {
#    # use tcp connection
#    # server  127.0.0.1:9000;
#    # or socket
#    server   unix:/var/run/php/php7.0-fpm.sock;
# }
# server {
#    listen 80;
#    server_name mage.dev;
#    set $MAGE_ROOT /var/www/magento2;
#    set $MAGE_DEBUG_SHOW_ARGS 1;
#    include /vagrant/magento2/nginx.conf.sample;
# }
#
## Optional override of deployment mode. We recommend you use the
## command 'bin/magento deploy:mode:set' to switch modes instead.
##
## set $MAGE_MODE default; # or production or developer
##
## If you set MAGE_MODE in server config, you must pass the variable into the
## PHP entry point blocks, which are indicated below. You can pass
## it in using:
##
## fastcgi_param  MAGE_MODE $MAGE_MODE;
##
## In production mode, you should uncomment the 'expires' directive in the /static/ location block

root $MAGE_ROOT/pub;

index index.php;
autoindex off;
charset UTF-8;
error_page 404 403 = /errors/404.php;
#add_header "X-UA-Compatible" "IE=Edge";


# Deny access to sensitive files
location /.user.ini {
    deny all;
}

# PHP entry point for setup application
location ~* ^/setup($|/) {
    root $MAGE_ROOT;
    location ~ ^/setup/index.php {
        fastcgi_pass   fastcgi_backend;

        fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
        fastcgi_param  PHP_VALUE "memory_limit=756M \n max_execution_time=600";
        fastcgi_read_timeout 600s;
        fastcgi_connect_timeout 600s;

        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }

    location ~ ^/setup/(?!pub/). {
        deny all;
    }

    location ~ ^/setup/pub/ {
        add_header X-Frame-Options "SAMEORIGIN";
    }
}

# PHP entry point for update application
location ~* ^/update($|/) {
    root $MAGE_ROOT;

    location ~ ^/update/index.php {
        fastcgi_split_path_info ^(/update/index.php)(/.+)$;
        fastcgi_pass   fastcgi_backend;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param  PATH_INFO        $fastcgi_path_info;
        include        fastcgi_params;
    }

    # Deny everything but index.php
    location ~ ^/update/(?!pub/). {
        deny all;
    }

    location ~ ^/update/pub/ {
        add_header X-Frame-Options "SAMEORIGIN";
    }
}

location / {
    try_files $uri $uri/ /index.php$is_args$args;
}

location /pub/ {
    location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
        deny all;
    }
    alias $MAGE_ROOT/pub/;
    add_header X-Frame-Options "SAMEORIGIN";
}

location /static/ {
    # Uncomment the following line in production mode
    # expires max;

    # Remove signature of the static files that is used to overcome the browser cache
    location ~ ^/static/version {
        rewrite ^/static/(version\d*/)?(.*)$ /static/$2 last;
    }

    location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2|json)$ {
        add_header Cache-Control "public";
        add_header X-Frame-Options "SAMEORIGIN";
        expires +1y;

        if (!-f $request_filename) {
            rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
        }
    }
    location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
        add_header Cache-Control "no-store";
        add_header X-Frame-Options "SAMEORIGIN";
        expires    off;

        if (!-f $request_filename) {
           rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
        }
    }
    if (!-f $request_filename) {
        rewrite ^/static/(version\d*/)?(.*)$ /static.php?resource=$2 last;
    }
    add_header X-Frame-Options "SAMEORIGIN";
}

location /media/ {
    try_files $uri $uri/ /get.php$is_args$args;

    location ~ ^/media/theme_customization/.*\.xml {
        deny all;
    }

    location ~* \.(ico|jpg|jpeg|png|gif|svg|js|css|swf|eot|ttf|otf|woff|woff2)$ {
        add_header Cache-Control "public";
        add_header X-Frame-Options "SAMEORIGIN";
        expires +1y;
        try_files $uri $uri/ /get.php$is_args$args;
    }
    location ~* \.(zip|gz|gzip|bz2|csv|xml)$ {
        add_header Cache-Control "no-store";
        add_header X-Frame-Options "SAMEORIGIN";
        expires    off;
        try_files $uri $uri/ /get.php$is_args$args;
    }
    add_header X-Frame-Options "SAMEORIGIN";
}

location /media/customer/ {
    deny all;
}

location /media/downloadable/ {
    deny all;
}

location /media/import/ {
    deny all;
}
location /errors/ {
    location ~* \.xml$ {
        deny all;
    }
}

# PHP entry point for main application
location ~ ^/(index|get|static|errors/report|errors/404|errors/503|health_check)\.php$ {
    try_files $uri =404;
    fastcgi_pass   fastcgi_backend;
    fastcgi_buffers 1024 4k;

    fastcgi_param  PHP_FLAG  "session.auto_start=off \n suhosin.session.cryptua=off";
    fastcgi_param  PHP_VALUE "memory_limit=756M \n max_execution_time=18000";
    fastcgi_read_timeout 600s;
    fastcgi_connect_timeout 600s;

    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    include        fastcgi_params;
}

gzip on;
gzip_disable "msie6";

gzip_comp_level 6;
gzip_min_length 1100;
gzip_buffers 16 8k;
gzip_proxied any;
gzip_types
    text/plain
    text/css
    text/js
    text/xml
    text/javascript
    application/javascript
    application/x-javascript
    application/json
    application/xml
    application/xml+rss
    image/svg+xml;
gzip_vary on;

# Banned locations (only reached if the earlier PHP entry point regexes don't match)
location ~* (\.php$|\.phtml$|\.htaccess$|\.git) {
    deny all;
}

```

**Comment by jaredpetersen** [comment]
This problem hit me as well when using the oneliner install. Several files were turned into empty directories instead, not just `nginx.conf.sample`. Just replacing the nginx file with the above snippet didn't work as a result.

The workaround for me was to use the manual installation steps in the README up to the point where it has you run `bin/download`. I downloaded the file myself, decompressed it using the Mac GUI, and copied in the resulting artifacts to a src directory. After that, you can continue on with the manual install process without any hiccups. I suspect something is wrong with the tar command but I'm not sure what specifically.

**Comment by henrikmaa** [comment]
None of the above worked for me, still an issue.

Tried the one liner install.
manual install
manual install, adding src manually after decompressing with mac gui.
manual install, creating nginx.conf.sample file with code from comment further up.

**Comment by badgeekluck** [comment]
I am using same docker-compose template but changed compose.yml to this:
# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 32.0.1

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.18-2
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: markoshust/magento-php:7.3-fpm-6
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0

  elasticsearch:
    image: markoshust/magento-elasticsearch:7.6.2-2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.3-fpm-6
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:


I have a problem, which is:

after docker-compose up 

db_1             | 2020-10-05T13:11:16.691267Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1             | 2020-10-05T13:11:16.693086Z 0 [Note] mysqld (mysqld 5.7.31-34) starting as process 1 ...
db_1             | 2020-10-05T13:11:16.698216Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1             | 2020-10-05T13:11:16.698285Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1             | 2020-10-05T13:11:16.698322Z 0 [Note] InnoDB: Uses event mutexes
db_1             | 2020-10-05T13:11:16.698337Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1             | 2020-10-05T13:11:16.698352Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.7
db_1             | 2020-10-05T13:11:16.698389Z 0 [Note] InnoDB: Using Linux native AIO
db_1             | 2020-10-05T13:11:16.698713Z 0 [Note] InnoDB: Number of pools: 1
db_1             | 2020-10-05T13:11:16.699552Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1             | 2020-10-05T13:11:16.701387Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1             | 2020-10-05T13:11:16.709046Z 0 [Note] InnoDB: Completed initialization of buffer pool
app_1            | 2020/10/05 13:11:17 [crit] 1#1: pread() "/var/www/html/nginx.conf" failed (21: Is a directory)
phpfpm_1         | [05-Oct-2020 13:11:17] NOTICE: fpm is running, pid 1
db_1             | 2020-10-05T13:11:16.712122Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
phpfpm_1         | [05-Oct-2020 13:11:17] NOTICE: ready to handle connections
app_1            | nginx: [crit] pread() "/var/www/html/nginx.conf" failed (21: Is a directory)
db_1             | 2020-10-05T13:11:16.723621Z 0 [Note] InnoDB: Crash recovery did not find the parallel doublewrite buffer at /var/lib/mysql/xb_doublewrite
db_1             | 2020-10-05T13:11:16.724526Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1             | 2020-10-05T13:11:16.740839Z 0 [Note] InnoDB: Created parallel doublewrite buffer at /var/lib/mysql/xb_doublewrite, size 3932160 bytes
redis_1          | 1:C 05 Oct 2020 13:11:16.320 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 05 Oct 2020 13:11:16.320 # Redis version=5.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 05 Oct 2020 13:11:16.320 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
db_1             | 2020-10-05T13:11:16.750373Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1             | 2020-10-05T13:11:16.750584Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1             | 2020-10-05T13:11:16.781213Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1             | 2020-10-05T13:11:16.782463Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1             | 2020-10-05T13:11:16.782535Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1             | 2020-10-05T13:11:16.783786Z 0 [Note] InnoDB: Percona XtraDB (http://www.percona.com) 5.7.31-34 started; log sequence number 12081483
db_1             | 2020-10-05T13:11:16.784480Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1             | 2020-10-05T13:11:16.792208Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
redis_1          | 1:M 05 Oct 2020 13:11:16.321 * Running mode=standalone, port=6379.
redis_1          | 1:M 05 Oct 2020 13:11:16.321 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | 1:M 05 Oct 2020 13:11:16.321 # Server initialized
redis_1          | 1:M 05 Oct 2020 13:11:16.321 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
db_1             | 2020-10-05T13:11:16.795151Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1             | 2020-10-05T13:11:16.795192Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1             | 2020-10-05T13:11:16.795328Z 0 [Note] InnoDB: Buffer pool(s) load completed at 201005 13:11:16
db_1             | 2020-10-05T13:11:16.796142Z 0 [Warning] CA certificate ca.pem is self signed.
db_1             | 2020-10-05T13:11:16.796198Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
redis_1          | 1:M 05 Oct 2020 13:11:16.322 * Ready to accept connections
db_1             | 2020-10-05T13:11:16.796666Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1             | 2020-10-05T13:11:16.796766Z 0 [Note] IPv6 is available.
db_1             | 2020-10-05T13:11:16.796807Z 0 [Note]   - '::' resolves to '::';
db_1             | 2020-10-05T13:11:16.796829Z 0 [Note] Server socket created on IP: '::'.
db_1             | 2020-10-05T13:11:16.840817Z 0 [Note] Event Scheduler: Loaded 0 events
db_1             | 2020-10-05T13:11:16.842298Z 0 [Note] mysqld: ready for connections.
db_1             | Version: '5.7.31-34'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  Percona Server (GPL), Release 34, Revision 2e68637
tbs-docker_app_1 exited with code 1



as you see tbs-docker_app_1 is closing. I could not find why.

app_1            | 2020/10/05 13:11:17 [crit] 1#1: pread() "/var/www/html/nginx.conf" failed (21: Is a directory)
app_1            | nginx: [crit] pread() "/var/www/html/nginx.conf" failed (21: Is a directory)

It is realy directory, but i could not find how this shit happening. :)

**Comment by coroo** [comment]
I've the same issue, not sure why.

The way I solve it by stop all the container, delete it include the volumes in docker.
Then remove the folder ~Sites/magento and retry to create a project again.

It solved mine by retry all the setup.
