### ISSUE TITLE
markoshust/magento-php:7.2-fpm-3 not found

### ISSUE THREAD

**Issue by greg-seedcloud** [markshust/docker-magento#167]
when running the latest one liner, it fails with:

```ERROR: manifest for markoshust/magento-php:7.2-fpm-3 not found```

If I break it into manual steps and replace with fpm-2 in the docker-compose file, it works again.

**Comment by markshust** [comment]
Thanks for the report. For some reason the last build failed. Looking into it right now.

**Comment by markshust** [comment]
The `php` base docker images upgraded from Stretch to Buster and it broke a lot of stuff https://github.com/docker-library/php/issues/865

I'm locking this back to Stretch based on the recommended tag and will issue a rebuild. It will fix this very shortly. Thanks for the report!

**Comment by zamartz** [comment]
Is there any ETA on this fix or last recommended version to use?

**Comment by markshust** [comment]
I just pushed out an update. Docker Hub is rebuilding the image now so.... 10-15 min?

**Comment by markshust** [comment]
It took a bit longer because Docker Hub was caching the last build, but I just rebuilt it and tag `7.2-fpm-3` is all complete. I'll rebuild all of the other tags now.

FYI I'm changing my process to not update docker-compose.yml files before the Docker Images have completed building so this doesn't happen again 😄 

Cheers,
Mark
