### ISSUE TITLE
Add ability to use magento2 github repo SHA/branch instead of tagged releases

### ISSUE THREAD

**Issue by filmaj** [markshust/docker-magento#183]
It seems like the current implementation via [`bin/download` requires the use of tagged releases of magento2  via Nexcess distributions](https://github.com/markshust/docker-magento/blob/master/compose/magento-2/bin/download).

It would be cool to also support leveraging the magento2 github repo and be able to specify arbitrary repo SHAs.

Per @markshust on Slack, it sounds like we'd need to look at how the Nexcess distributions differ from the GitHub repo:

> note that github has a different file structure than things like the nexcess archives or composer installs — we definitely want to follow the nexcess/composer format of putting all the core code in vendor instead of `app/code/Magento` like github does

As a Magento newb, I still need  to figure out all these differences but I am down for investigating and trying to tackle this! I'd also love to hear if this is a desirable feature from other project community members.

**Comment by markshust** [comment]
tagging for community

**Comment by dmanners** [comment]
I have just setup a local contribution env today with the new project steps.

Instead of running:

   `composer create-project --repository=https://repo.magento.com/ --ignore-platform-reqs magento/project-community-edition=2.3.3 src`

I ran:

    `git clone git@github.com:dmanners/magento2.git src`

And then followed on the steps afterwards and everything seemed to be fine, though I have literally just finished the installation step with xdebug the frontend and admin do seem to work as expected.

**Comment by markshust** [comment]
I'm closing this as the above steps work (same as "existing projects" step, but with `git clone` vs `composer create-project`

Note that because Magento code is located in `app/code/Magento`, there will be performance issues if you are not running in a linux environment. There is no workaround for this due to Docker filesystem limitations.
