### ISSUE TITLE
An exception was raised while creating "Request"; no instance returned

### ISSUE THREAD

**Issue by abhinavaggarwal8** [markshust/docker-magento#204]
**Description**
I have updated the docker images using bin/update and then i am not able to use any Magento commands inside the phpfpm container in -it mode

**Steps To Reproduce**
1. update using bin/update

**Expected Result**
should run all required Magento commands

**Actual Result**
An exception was raised while creating "Request"; no instance returned
![image](https://user-images.githubusercontent.com/10917770/70390698-57dbee80-19f3-11ea-8971-041a9c7a16d1.png)

**Comment by markshust** [comment]
I'm unable to replicate -- do you know what version of docker-magento you were running before running `bin/update`?

**Comment by markshust** [comment]
Closing as unable to replicate. FYI I updated the `bin/update` CLI script in 26.0.0 so you will probably need to re-download `bin/update` anyways. See https://github.com/markshust/docker-magento/#older-versions

**Comment by crowe00** [comment]
@markshust I am having this same issue here today with running `bin/magento app:config:import` and really, any `bin/magento` commands. Doing some research on this error points to it being a mismatch in PHP versions. I'm trying to run magento 2.2.5 (slightly behind latest) with PHP 7.1. I had to do `--ignore-platform-reqs` on composer install because there were a series of issues with the PHP and the modules in my composer.json.

**Comment by crowe00** [comment]
Actually answered my own question I believe, but leaving it all here for visibility. After looking through the issues I saw how to change over to `markoshust/magento-php:7.1-fpm-9` to use PHP7.1. Once I rebooted up with that in the docker-compose.yml those previous issues and commands went away.
