### ISSUE TITLE
Magento web setup wizard

### ISSUE THREAD

**Issue by Elema82** [markshust/docker-magento#218]
Hello again @markshust, first im sorry for this new issue but I didn't find a way for use on my store the Magento web setup wizard for install new extensions from marketplace.

When I try to enter on Web Setup Wizard in my menu this link redirect to "https://magento2.test:8443/setup/" and my browser return this error "ERR_CONNECTION_REFUSED"

And this is my information about my ports:
<img width="926" alt="Captura de Pantalla 2020-02-06 a la(s) 14 57 55" src="https://user-images.githubusercontent.com/25822930/73965695-62cbd600-48f3-11ea-9f19-31d80d76f626.png">

what do you think? I forgot config something?

**Comment by markshust** [comment]
I would avoid the Web Setup Wizard completely, as it's aimed for non-developers. You're going to want to use composer and the `bin/magento` cli to setup and install modules.

I'm going to close this out since I don't think anyone uses the Web Setup Wizard (and it's not something I would personally focus on fixing ever), but if you wanted to make a PR for this fix I would gladly take it in!
