### ISSUE TITLE
Requesting Steps or a Video to install Sample Data.

### ISSUE THREAD

**Issue by kishennagaraju** [markshust/docker-magento#249]
Hello,

I am trying to install the magento 2 docker setup by using the automated install command in Mac OS Mojave. After executing the command I can see all the magento commands list by running the command "bin/magento list".

However when I run the commands "bin/magento sampledata:deploy" and "bin/magento setup:upgrade", the sample data is not being installed into my magento 2 container and there is no exception log being generated in my container.

I wanted to know if there is any example (any link or video would be highly appreciated) for installing Sample Data ?

Thanks in advance.

**Comment by kishennagaraju** [comment]
Hello,

Is there any update on this ?

**Comment by markshust** [comment]
Hi @kishennagaraju, did you want to hop on a Google Hangout? I have a few to go over this with you and find out why the sample data isn't showing up.

**Comment by kishennagaraju** [comment]
Sure. Please send me the link.

**Comment by markshust** [comment]
To join the video meeting, click this link: https://meet.google.com/tus-tput-bzy
Otherwise, to join by phone, dial +1 515-512-9725 and enter this PIN: 934 006 717#

**Comment by kishennagaraju** [comment]
Attaching the screenshot as requested.
![Screenshot 2020-04-13 at 10 56 10 PM](https://user-images.githubusercontent.com/41683536/79142998-0ba61e00-7dda-11ea-9a81-81a49b05c4d3.png)

**Comment by markshust** [comment]
@kishennagaraju made a couple more updates, you can reference them in the code above. a `bin/update` should bring it all up to date.

again, it was great chatting with you!

**Comment by markshust** [comment]
@kishennagaraju i implemented a more elegant solution to this in the `bin/magento` script. this will disable the `Temando_Shipping` module but only during a sample data deployment. I'm automatically running setup:upgrade also so that we can toggle the `Temando_Shipping` module back on afterwards. it's possible not having this module enabled will cause other issues throughout Magento in the admin, since the backend attribute source would no longer exist for installed attributes. https://community.magento.com/t5/Installing-Extensions/temando-CRITICAL-quot-accountId-quot-is-required-Enter-and-try/td-p/143132/page/2

this should be all set now!
