### ISSUE TITLE
Configurable Product's Sample Data is not being installed after disabling the Temando Shipping Module

### ISSUE THREAD

**Issue by kishennagaraju** [markshust/docker-magento#250]
Hello Mark,

When I run the "bin/magento sampledata:deploy" command, as per the code, after disabling the Temando_Shipping Module, the sample data is not being installed in the magento application whereas the other data such as the grouped product data and simple product data are being installed perfectly.

My RAM is set to 4 GB and Swap to 2 GB in docker preferences. I am facing this issue in my Macbook pro mid 2012 edition.

Can you please check this when you have time ?

Regards,
Kishen.

**Comment by markshust** [comment]
Hi @kishennagaraju, thanks for the report, I'll check this out as soon as I can! Mark

**Comment by kishennagaraju** [comment]
Hello Mark,

Any Updates on this ?

Thanks,
Kishen.

**Comment by markshust** [comment]
@kishennagaraju I finally got a chance to look at this, and can confirm this is happening. It looks like the jacket isn't even being inserted into the database, since it's not coming up from the admin.

At the moment, it's better to have some sample data rather than no sample data, so I think this is an improvement to the failed sample data installation that was happening before. I think the real solution would be to find a way to completely disable the Temando_Shipping module before *Magento* is installed, so it never knows about it in the first place. Something is conflicting with that module that causes this to happen. Either that, or we can fix the root issue with the Temando module conflicting with the Magento sample data.

I don't have a timeline on this (busy on other tasks), but will keep it open so that someone else could perhaps chime in here.

**Comment by kishennagaraju** [comment]
Thanks Mark, Please let me know when there are any updates. In the meanwhile I will try one of your suggested solutions from my end and will see if I have any luck.

**Comment by rangerz** [comment]
@markshust @kishennagaraju For my case I can't disable Temando_Shipping before run the sampledata:deploy.

My steps are here and import everything perfectly.
```
mkdir ~/Sites/magento2.test
cd ~/Sites/magento2.test
curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.3.4
./bin/cli bin/magento sampledata:deploy
./bin/cli bin/magento setup:upgrade

# and wait for long time to finish and check https://magento2.test site
```

My mac docker desktop setting is here:
![image](https://user-images.githubusercontent.com/3338473/80056347-9f1dd400-84e9-11ea-9be9-483061f39b0c.png)

**Comment by kishennagaraju** [comment]
Hello @rangerz,

Tried with the above mentioned steps with the same docker configurations but still the sample data for configurable products is not installing/importing.

Regards,
Kishen.

**Comment by markshust** [comment]
This is odd, because I'm able to replicate @kishennagaraju's issue. I'm wondering if something is going on specific to this Docker setup now. I ran through the entire install using Valet and the sample data installed perfectly (without doing anything with the Temando_Shipping module).

For me it's hanging up at:
```
...
Module 'Magento_Ui':
Module 'Magento_GoogleShoppingAds':
Module 'Magento_BundleGraphQl':
Module 'Magento_PageCache':
Module 'Magento_GroupedCatalogInventory':
Module 'Magento_GroupedImportExport':
Module 'Magento_CatalogSampleData':
```

**Comment by markshust** [comment]
I take that back.... it hung up for quite a while on that `Magento_CatalogSampleData` line, and then also on every `Magento_*SampleData` line, but everything eventually completed (over an hour for me on my 2018 MBP).

There's definitely a misconfigured config value someplace, perhaps in the PHP container, because it definitely did not take this long before. It used to take ~5 minutes or so. I'm going to double check the config to see what has changed recently.

I'm going to back out the updates to the `bin/magento` helper script as well, as while it was taking a long time to complete, it did in fact complete with the Temando_Shipping module enabled.

@kishennagaraju note that I'm still getting this error:
```
temando.CRITICAL: "accountId" is required. Enter and try again. {"exception":"[object] (Magento\\Framework\\Exception\\InputException(code: 0): \"accountId\" is required. Enter and try again. at /var/www/html/vendor/magento/framework/Exception/InputException.php:91)"} []
```
...however, it doesn't seem to affect the sample data installation as it does complete successfully, even with that error.

**Comment by kishennagaraju** [comment]
Hello @markshust - I have enabled the Temando_Shipping module while installing the sampledata but still no luck.

**Comment by markshust** [comment]
Closing this ticket out in favor of https://github.com/markshust/docker-magento/issues/257

**Comment by markshust** [comment]
@kishennagaraju your install may be failing because of less memory on the machine, as @rangerz and I can both complete sample data installation. It just takes a very long time to complete execution. It is most likely not completing on your machine due to the "memory thrashing" issue we chatted about previously, but on a high powered enough machine it is completing.

Once we resolve the root issue of https://github.com/markshust/docker-magento/issues/257 it should also resolve your the memory issue. Something funky is going on here.

**Comment by markshust** [comment]
@kishennagaraju see updated comment at https://github.com/markshust/docker-magento/issues/257#issuecomment-622043696

**Comment by markshust** [comment]
@kishennagaraju wondering if the performance issues were related to docker for mac. see ticket https://github.com/docker/for-mac/issues/4423

I presume this is the case, as nothing really changed in this repo that would affect performance this year, and the setup worked perfectly previously.

A new version of Docker for Mac is out today, version 2.3.0.2. I would recommend upgrading and try again.
