### ISSUE TITLE
Unable to setup the magento using onlinesetup and Manual process on Windows docker toolbox

### ISSUE THREAD

**Issue by krishnathokala** [markshust/docker-magento#252]
Hi Team,

I tried setting up the magento using the onelinesetup and i am getting the attached error. Could any one help me in setting up the environment.

Operating system: Windows 8.1
Docker: Docker toolbox for windows
[onelinesetup-error.txt](https://github.com/markshust/docker-magento/files/4509522/onelinesetup-error.txt)

Thanks & Regards,
Krishna Thokala.

**Comment by markshust** [comment]
Hi @krishnathokala,

You're going to have to use WSL if you want to run this on Windows. Even then, the install may not go entirely smooth (the project is really only supported for Linux and macOS at this time, however it *should* work on Windows with WSL.

If you are able to figure this out on WSL and this project needs some tweaks in order to get it to run, I'd gladly take in a contribution to either document the changes needed to get this to run on WSL or any modifications needed for this project.
