### ISSUE TITLE
Add a Mac / Linux detector

### ISSUE THREAD

**Issue by gander** [markshust/docker-magento#266]
You need to add a script that detects whether the system is Mac or not. On this basis, you can make properly working scripts. They will then be used to create command variants that work only on Linux or only on Mac.

Examples:
```bash
#!/usr/bin/env bash

if [ "$(uname)" == "Darwin" ]; then
    return true
else
    return false
fi
```
```bash
#!/usr/bin/env bash

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac
return ${machine}
```

Source: https://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux

**Comment by rangerz** [comment]
is it for `sed` of #251 ?
I think It would be better to find a general method to replace the string or other any thing.

For example
```
sed -i.bak 's/foo/bar/g' misc.xml && rm $_.bak

# or

perl -i -pe 's/foo/bar/g' file
```

I tested it can work for linux and mac 10.15.4, and please ignore the old version of mac

**Comment by gander** [comment]
Not only for that. Adding an SSL certificate does not work properly because there is no `security` command in Linux, and the system-detection would allow the use of an appropriate command.

**Comment by markshust** [comment]
We do need an easy way to detect linux/mac. I'll checkout the above scripts.

**Comment by markshust** [comment]
This line actually works great: `if [ "$(uname)" == "Darwin" ]; then`

We don't really need Windows or Linux detection, because you're either on Linux (with Ubuntu or Windows WSL) or on Mac.

However, I don't think we need a separate script for this. I think we may be moving mkcert to the host as noted in https://github.com/markshust/docker-magento/issues/222#issuecomment-602063057 -- I really hate host dependencies, but SSL is confusing and this would help out a lot.

**Comment by markshust** [comment]
I just backtracked on what I just said 😂

I implemented the above line in `bin/setup-ssl-ca` (see https://github.com/markshust/docker-magento/issues/222#issuecomment-666269382). This is very non-invasive. Let's see if this works. Thanks for the example scripts 👍
