### ISSUE TITLE
Introduce custom JS

### ISSUE THREAD

**Issue by icychocolate98** [markshust/docker-magento#281]
I want to introduce a custom script on my magento <head> tag in index but I can't find file.
I found it should be here "app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml", but my app/code folder is empty, could anyone tell me something about where I can add my custom scripts on this Magento deployment?

Thanks a lot!

**Steps To Reproduce**
1. Add script on <head> store tag.

**Expected Result**
Script working.

**Actual Result**
I can't find default_head_blocks.xml

**Comment by markshust** [comment]
Magento dependencies are installed with Composer, so instead of looking at `app/code/Magento`, you will find the same file structure & files instead within `vendor/magento`.

Note that you'll not want to modify any file within the `vendor` folder though. To add scripts you'll want to create a custom module and follow all of the standard workings of adding a custom javascript file to your store.

https://devdocs.magento.com/guides/v2.3/javascript-dev-guide/javascript/custom_js.html
