### ISSUE TITLE
Magento 2.4 not able to be installed directly with sample data

### ISSUE THREAD

**Issue by km-at-aloteq-dev** [markshust/docker-magento#288]
**Description**
Scripts can't download magento 2.4 sources, because file doesn't exists

**Steps To Reproduce**
1. start online automatic setup (or manual with version 2.4)

**Expected Result**
Download should happen and ./src folder should have files

**Actual Result**
Download doesn't happen and ./src folder is empty
Console output is:
```$ curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test with-samples-2.4.0
Initialized empty Git repository in /mnt/d/projects/magento2/.git/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   252  100   252    0     0    682      0 --:--:-- --:--:-- --:--:--   681
Extracting magento2-with-samples-2.4.0.tar.gz to ./src

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
The reason is that folder http://pubfiles.nexcess.net/magento/ce-packages/ doesn't contain 2.4 version at the moment

In general scripts doesn't have any error handling. But just adding `set -e` at the script beginning. [Docs](https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin)

**Comment by markshust** [comment]
Hi @km-at-aloteq-dev, yes, the reason this is happening is due to Nexcess not uploading archives. I built-in a fallback to use hypernode at https://github.com/markshust/docker-magento/blob/master/compose/bin/download#L11 in the event an archive cannot be downloaded from Nexcess, which is why the standard install without sampledata is working. However, their servers don't provide bundled archives to use with sample data.

The workaround right now is to install Magento 2 without sample data, then install the sample data after install with:

```
bin/magento sampledata:deploy
bin/magento setup:upgrade
```

I'll keep this ticket open though for visibility and I updated the name of this ticket to be more reflective of the issue.

**Comment by markshust** [comment]
Pinging @clwells -- you are probably not the right contact here, but perhaps you can ping someone over at Nexcess into this conversation 😄

**Comment by clwells** [comment]
@ ChrisOrlando can probably assist.

**Comment by ChrisOrlando** [comment]
2.4.0 has been uploaded

**Comment by markshust** [comment]
@ChrisOrlando awesome, thanks a bunch Chris 🎉
