### ISSUE TITLE
Support for Kubernetes

### ISSUE THREAD

**Issue by dvanmali** [markshust/docker-magento#291]
Fantastic job on this repository! You have the cleanest Magento code that I have found, thank you.

I know this may take time to rework, but it would be fantastic to add Kubernetes support. I've been trying to add support myself, but some of the internal files seem reliant on the Nginx `cert/` files, Docker persistent volumes in the `docker-compose.yml` file, and setup functions in the `bin/` folder. Would you be possible to add this support?

**Comment by markshust** [comment]
Hi @dvanmali, thanks for this request. If I do add Kubernetes support, it will almost assuredly be a commercial offering as I cannot & do not wish to support that complex of a system without getting compensated for it :) It will also take some architectural updates to this project in order to make this work. I don't have any plans to imminently do any of this unfortunately.
