### ISSUE TITLE
Question about where / when is the nginx.conf file is created?

### ISSUE THREAD

**Issue by carylewis** [markshust/docker-magento#333]
Can someone please provide details as to when the nginx.conf file is created?

Does it happen as part of the composer --create-project execution, or the bin/setup process?

**Comment by rangerz** [comment]
The `nginx.conf` setting is in `docker-compose.dev.yml`

```
- ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
```

It's triggered by `bin/start`

Not happen in `composer --create-project` and `bin/setup`, but they both will create `nginx.config.sample`

**Comment by markshust** [comment]
If you are referencing the main `nginx.conf` file defined in the server-level, it is actually built when the image is created.

Here is the file in the repo: https://github.com/markshust/docker-magento/blob/master/images/nginx/1.18/conf/nginx.conf

It's added to the image in the Dockerfile at https://github.com/markshust/docker-magento/blob/master/images/nginx/1.18/Dockerfile#L23

The project-specific file is created upon Magento setup, and is located in the project root and named `nginx.conf.sample`. It's added as a bounded volume mount at container start at https://github.com/markshust/docker-magento/blob/master/compose/docker-compose.dev.yml#L17

The file is included in the Nginx config at https://github.com/markshust/docker-magento/blob/master/images/nginx/1.18/conf/default.conf#L22

The reference to `[.]` in `include /var/www/html/nginx[.]conf;` is a special syntax. If the file doesn't exist, it won't load it.

If you need to modify the `nginx.sample.conf` file, copy it to `nginx.conf`, make your updates, and then change the volume mount to look at `nginx.conf` instead of `nginx.sample.conf`, then restart the containers.
