### ISSUE TITLE
Run bin/setup with error (Macos Catalina)(Magento 2.4.1) 

### ISSUE THREAD

**Issue by truonghdpk** [markshust/docker-magento#345]
**Description**
i have deploy magento docker with manually setting but got some error

**Steps To Reproduce**
1. curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
2. bin/download 2.4.1
3. echo "127.0.0.1 ::1 magento2.test" | sudo tee -a /etc/hosts
4. bin/setup magento2.test

**Expected Result**
must restart docker-container and run with no error
**Actual Result**
`Creating volume "docker-magento3_appdata" with default driver
Creating volume "docker-magento3_dbdata" with default driver
Creating volume "docker-magento3_rabbitmqdata" with default driver
Creating volume "docker-magento3_sockdata" with default driver
Creating volume "docker-magento3_ssldata" with default driver
Creating docker-magento3_elasticsearch_1 ... done
Creating docker-magento3_db_1            ... done
Creating docker-magento3_redis_1         ... done
Creating docker-magento3_rabbitmq_1      ... done
Creating docker-magento3_phpfpm_1        ... done
Creating docker-magento3_app_1           ... done
Copying all files from host to container...
Completed copying all files from host to container
Correcting filesystem ownerships...
Filesystem ownerships corrected.
Correcting filesystem permissions...
find: 'var': No such file or directory
find: 'vendor': No such file or directory
find: 'pub/static': No such file or directory
find: 'pub/media': No such file or directory
find: 'app/etc': No such file or directory
chmod: cannot access 'bin/magento': No such file or directory
Filesystem permissions corrected.
chmod: cannot access 'bin/magento': No such file or directory
Forcing reinstall of composer deps to ensure perms & reqs...
Changed current directory to /var/www/.composer
Using version ^0.3.10 for hirak/prestissimo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)`
![Screen Shot 2020-11-10 at 00 24 54](https://user-images.githubusercontent.com/45913828/98574949-28acbc00-22eb-11eb-85ac-1afd43d63c43.png)
![Screen Shot 2020-11-10 at 00 25 34](https://user-images.githubusercontent.com/45913828/98575028-411cd680-22eb-11eb-9d7b-e3da7e47aba9.png)

**Comment by ivancunha** [comment]
Oh!!!! Someone with the same problem as me!!! But I'm on Ubuntu 20.04!
I've been trying this since yesterday and nothing!
First upgraded Composer to Composer 2.... and had problem with the plugin hirak/prestissimo not being used anymore and even uninstalling it (https://github.com/hirak/prestissimo#announcement-composer-2-is-now-available) I had to go back to Composer 1.... and those were the first 5hours of my journey!
Meanwhile.... 

I've bean using the one line automated setup:
`curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bash -s -- magento2.test 2.4.1
`
And I get this problem:
```
curl: (22) The requested URL returned error: 404 Not Found
find: ‘/home/ivancunha/.docker-magento/magento2-2.4.1.tar.gz’: No such file or directory
Archive not found, or not yet available due to new version release.
Attempting install with Composer...
```
Then it goes on and installs everything... until I get almost the same as in your printscreens.... and 
`You may now access your Magento instance at https://magento2.test/`

It's 19h30 and after a day of not working I've just installed 2.4.0 without a problem.... so I can pull an all nighter and get something done :\

**Comment by markshust** [comment]
I'm thinking this might have something to do with https://github.com/markshust/docker-magento/issues/336 -- none of the scripts should rely on a locally-installed Composer install.

That said, I need to get on Nexcess and HyperNode about them not getting the archives up for 2.4.1 yet, as this version has been out for some time now. There have been delays in both of those mirrors in getting an archive up when it is publicly available. In my opinion, their process should be somewhat automated and available on Magento launch day.

I'd like to be able to build these archives myself if possible. If anyone can get steps on how they build these archives, I can put this within some sort of serverless function which perhaps I can tie to Magento's release tags, so we never have to worry about archives missing again.

**Comment by brunocastello** [comment]
Mine fails with a _Required parameter 'theme_dir' was not passed_ error when I try the 2.4.1 with samples. I had to install the 2.3.1 with samples.

**Comment by markshust** [comment]
FYI this has been resolved, if there are any errors mounting volumes, the script exits.
