### ISSUE TITLE
How to set COMPOSER_MEMORY_LIMIT=-1  in download script??

### ISSUE THREAD

**Issue by artmouse** [markshust/docker-magento#416]
How to set COMPOSER_MEMORY_LIMIT=-1 in download script??

**Comment by artmouse** [comment]
Close!
Add environment to phpfpm in docker-compose.yml

  phpfpm:
    image: markoshust/magento-php:7.4-fpm-5
    **environment:
      - COMPOSER_MEMORY_LIMIT=-1**
    links:
      - db
    volumes: *appvolumes

**Comment by markshust** [comment]
Thank you for updating your question with the solution. A lot of people just close out tickets, so much better to provide the solution before closing it out 👍 

I don't think this requires further documentation in this project, as it's just one of those things that is specific to Docker. If we documented everything docker-specific in this repo, there would be a lot of redundancy and eventually things may get out of date. Much better to provide a solution here and then close out (or perhaps even better yet, open up a GitHub Discussion on "how to", because it's not really even a bug or issue with this project).
