### ISSUE TITLE
bin/mysql < backups/magento.sql not work

### ISSUE THREAD

**Issue by GNUXDAR** [markshust/docker-magento#432]
**Description**
Hello.
i write bin/mysql < backups/magento.sql
the output is:

ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privile' at line 1
ERROR: 1

i create the backups folder with magento.sql files

**Comment by rangerz** [comment]
Your `magento.sql` file seems incomplete, and it includes `mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privile`

Try to use [n98-magerun2](https://github.com/netz98/n98-magerun2) to export database, command is `n98-magerun2.phar db:dump`

Good Luck

**Comment by GNUXDAR** [comment]
No, my magento.sql file is complete. but command bin/mysql < backups/magento.sql no work.
i solved.
$ bin/mysql
$ use magento
$ bin/copytocontainer magento.sql 	(inside  src folder)
$ source magento.sql

but modified the file apt/etc/env.php what is default  password and default user

**Comment by rangerz** [comment]
db setting is in `env/db.env`
```
MYSQL_HOST=db
MYSQL_ROOT_PASSWORD=magento
MYSQL_DATABASE=magento
MYSQL_USER=magento
```

**Comment by markshust** [comment]
This error:

```
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privile' at line 1
```

...is a MySQL error, and isn't at all any issue with this project. Not that you may need to run that import as `root` because your MySQL file is expecting escalated privileges.

Something like this should work:

`bin/cli mysql -hdb -uroot -pmagento magento < backups/magento.sql`

If it doesn't, you may want to find a way to modify your SQL backup file, as there is something funky going on there.
