### ISSUE TITLE
xDebug dont work 

### ISSUE THREAD

**Issue by r1tt3r** [markshust/docker-magento#455]
Hello everyone, im trying use docker-magento + phpstorm + xDebug, however when trying to debug in phpstorm show me the message that is displayed in the print below

![Captura de Tela 2021-05-03 às 19 36 18](https://user-images.githubusercontent.com/9289149/116942050-35c9b880-ac47-11eb-8163-223e9693fb7e.png)

I followed the README configuration steps, does anyone have any idea what it might be?

**Comment by Viper9x** [comment]
@r1tt3r let's try set Server name
https://github.com/markshust/docker-magento/issues/350#issuecomment-742219682

**Comment by markshust** [comment]
Unable to replicate, Xdebug works fine for me.

**Comment by Stoyvo** [comment]
Sorry @markshust - It's not working on MacOS - Big Sur, fresh repo, first docker instance ever created on this machine.
I believe the problem is when domains are provisioned. PHP_IDE_CONFIG is missing in response.
The error occurs:
![image](https://user-images.githubusercontent.com/6148099/130174329-34582099-c431-480b-9057-37d3fafac0aa.png)

I will mention, the debug set up in the configuration has a domain set, but no breakpoint will hit. Instead I must enable the listener for incoming connections, and only then can I accept an incoming request.

**Comment by markshust** [comment]
@Stoyvo does your Magento install work? The file `/var/www/html/pub/index.php` should definitely exist, both locally at `pub/index.php`, and within the container at the path specified. The fact that it's not finding this file tells me there may be another issue with your setup.

**Comment by Stoyvo** [comment]
@markshust Yes the Magento install worked. I can only receive connections on port 443 and not 9001/9003. This tells me the docker setup has a blocked port. If I accept port 443, the path mappings do not work in PHPSTORM 2021.2.1. I was unable to solve the issue and decided to move back to a vagrant setup, though I would love to revisit a docker setup.
