### ISSUE TITLE
Clarifications on the recommended project directory structure setup

### ISSUE THREAD

**Issue by radub** [markshust/docker-magento#461]
In the **Update** section of the documentation there is the following recommendation:

> We recommend keeping your docker config files in version control, so you can monitor the changes to files after updates. After reviewing the code updates and ensuring they updated as intended, run bin/restart to restart your containers to have the new configuration take effect.
> 
> It is recommended to keep your root docker config files in one repository, and your Magento code setup in another. This ensures the Magento base path lives at the top of one specific repository, which makes automated build pipelines and deployments easy to manage, and maintains compatibility with projects such as Magento Cloud.

What I understand from it is that the project's structure should have two main directories:
- docker-magento
- magento-code

This means that the default path for the magento code will have to change from **./src** to **../magento-code** in order for the code to be correctly mounted inside the app container.
Would it be enough to update the volume path(s) in the **docker-compose.yml.dev** file or are there other areas where the path should be adjusted? A quick search showed some references to the **src** directory in **bin/start** and **bin/copyfromcontainer** so I just want to make sure I have everything covered.

What is the recommended way to update this path?

Thanks!

**Comment by markshust** [comment]
That `./src` directory is used in a lot of places, and I don't have any plans to support alternate folder names.

And the project structure really isn't correct as noted, it is:
- ./docker-magento/
- ./docker-magento/src (for Magento source code)

Rather than using a `docker-magento` directory, I call it the name of the site I'm working on. So if I was working on `whatever.com`, I would place the project at:

`~/Sites/whatever.com`

This would be the folder that contains the `docker-magento` project. Then, the Magento source code for the `whatever.com` site would be located at:

`~/Sites/whatever.com/src`

Hope this makes sense! You shouldn't need to change any docker-compose YML files, config, or anything else -- it should all work with zero config changes.
