### ISSUE TITLE
Slow backend after upgrade to v2.4.3? - Not a markshust/docker-magento issue

### ISSUE THREAD

**Issue by craigfleming** [markshust/docker-magento#521]
I thought it would be useful to share an issue others could be facing after upgrading to Magento v2.4.3.

The very slow admin after upgrading to v2.4.3 is not related to markshust/docker-magento, but the max_session_size_admin default value in the Magento settings.

![130651168-b81ed86f-b5a2-46e3-a885-46d91b3e2490](https://user-images.githubusercontent.com/2504644/130701144-d958ef18-292b-4561-8326-bb5209ea449b.png)

If you can not access the admin to update the values, use the following CLI commands:

```
bin/magento config:set system/security/max_session_size_admin 512000
bin/magento config:set system/security/max_session_size_storefront 512000
```

Clean your cache and your admin backend should function at full speed.

@markshust  - You might want to consider adding this note to your readme as default Magento settings for max_session_size_admin seem to be causing a very slow admin experience (upwards of 30 seconds for admin page load) for many users who upgraded to Magento v2.4.3. I experienced no admin speed issues, up until I upgraded to v2.4.3 last week.

**Comment by markshust** [comment]
Hi Craig, thanks much for the report. Since this isn't related to this project, I'll just close this out for now, but if I hear it come up once or twice more, I'll add it to the readme. Just because this is a core Magento thing and not related to this project -- I usually side on not including those items in the README, as it would become unnecessarily large.
