### ISSUE TITLE
XDebug - Unable to read file in vendor

### ISSUE THREAD

**Issue by shinesoftware** [markshust/docker-magento#523]
Hello Mark, 

I have quickly configured a brand new Magento 2.4.2 project using your steps at the documentation into my own Ubuntu box. I am using the VSCode for develop our Magento extensions and I need the xdebug tool. 

After enable the xdebug by your script bin/xdebug enable I get a weird error

![screenshot_003](https://user-images.githubusercontent.com/1553035/131532892-6d20dcb4-f4b2-4109-9354-e762009bf3fa.jpg)

This is what I am seeing:

![screenshot_002](https://user-images.githubusercontent.com/1553035/131532928-ea9b46e2-7fe0-47f9-8b00-89955ad80bf2.jpg)

It seems to me that it doesn't resolve the src/vendor directory and it catch the root /vendor in the host server.

any hint?

[UPDATE]

I have changed the pathMapping in this way and it seems to me that works as well! Why this happens?

![screenshot_004](https://user-images.githubusercontent.com/1553035/131536788-7d0428ec-3a7d-4ab9-a1c7-6091a27a6ad2.jpg)

**Comment by markshust** [comment]
@shinesoftware ahh -- this was needed because you set your project root as the root of this project, containing all of the docker-compose.yml files, bin folder, etc. I always set my project root in the IDE (VS Code or PhpStorm) to the `src` directory, so I'm in the root of the Magento install instead. I think if you did this, your change wouldn't be needed.

**Comment by shinesoftware** [comment]
thanks @markshust I have solved!
