### ISSUE TITLE
mailcatcher is not working

### ISSUE THREAD

**Issue by makzef** [markshust/docker-magento#572]
**Description**
It seems mailcatcher is not working. Or I miss something.
I am not receiving any emails after registering the new account. 

So following the readme guide, I installed mageplaza/magento-2-smtp (by the way, need to correct the link) and configured it with host mailcatcher and port 1080. Mageplaza extension has a convenient tool to test sending emails from the admin panel. After long waiting, the test shows an error. I found the mailcather repository, where was mentioned port 1025. So I changed the port to 1025 in configuration and finally - it worked out and I receive emails (so I assume, need also to correct the port). 
But still, it does not work locally without third-party extensions where you can specify host and port.

**Steps To Reproduce**
 1. Register a new account on the newly installed docker-magento.

**Expected Result**
Receive email about registration (Welcome to Main Website Store email) on mailcather page - http://{yourdomain}:1080

**Actual Result**
There are no emails. In logs I always see this:
```
main.ERROR: Unable to send mail: Unknown error {"exception":"[object] (Laminas\\Mail\\Transport\\Exception\\RuntimeException(code: 0): Unable to send mail: Unknown error at /var/www/html/vendor/laminas/laminas-mail/src/Transport/Sendmail.php:298)"} []
```
**Additional Info**
Tested on Manjaro Linux
Kernel Version: 5.14.10-1-MANJARO (64-bit)
Magento 2.4.3-p1

**Comment by markshust** [comment]
Thanks for the report @makzef. I have confirmed that there should be no need for third-party smtp plugins now. That said, the fix is to have the sendmail path be:

```
sendmail_path = "/usr/bin/msmtp -t"
```

Per the ticket https://github.com/markshust/docker-magento/issues/556

It appears that the Docker image was cached, and/or for some reason the updates to the `php.ini` file were not applied. I'll be pushing out a new release for docker-magento shortly, and I'll be sure this file gets baked into the new images.

In the meantime, you can run `bin/root vi /usr/local/etc/php/php.ini`, replace the `sendmail_path` with the line above, save the file, then run `bin/restart` to apply the updates. After this, mailcatcher should work.

**Comment by markshust** [comment]
Fixed in `41.0.0`

**Comment by ileon777** [comment]
Hello @markshust 
I have error when sending email:
2022/03/29 09:52:21 dial tcp: lookup mailhog on 127.0.0.11:53: server misbehaving

I tried to change /usr/local/etc/php/php.ini:
from:
sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025"
to
sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailcatcher:1025"

But I doesn't help

**Comment by ileon777** [comment]
Hello @markshust
I fixed it by renaming the container from mailcatcher to mailhog in docker-compose.yaml


  mailhog:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
    extra_hosts: *appextrahosts
