### ISSUE TITLE
All files ends lines with ^M which makes install on Macs impossible.

### ISSUE THREAD

**Issue by sessan** [markshust/docker-magento#689]
When running your install on a Mac one needs to run dos2unix on all files. Otherwise nothing will work. 
It took me a while to figure out why... but when  all files are converted the setup works perfectly.  This also happens if one runs upgrade etc. since new files are downloaded.

**Comment by markshust** [comment]
I'm confused with the "makes install on Macs impossible" message, because this project was created for Macs, is mainly catered to Macs, and I've been using it on my Mac for 6 years now 🫤

I'm unable to replicate this error, and I'm guessing something is going on really funky on your machine, as I've installed this on completely clean installs of macOS and it works fine. I'm closing this out as unable to replicate.
