### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:367

### ISSUE THREAD

**Issue by boris1988** [markshust/docker-magento#695]
**Description**
Im trying to run bin/magento command and have an error

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
 git clone git@github.com:myrepo.git src
docker-compose -f docker-compose.yml up -d
bin/copytocontainer --all
bin/mysql < ../existing/magento.sql
bin/magento app:config:import

**Expected Result**
execute bin/magento 

**Actual Result**
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "bin/magento": stat bin/magento: no such file or directory: unknown
![Screenshot from 2022-04-26 16-33-52](https://user-images.githubusercontent.com/2422927/165311850-ff964025-2bb6-42a0-ad9a-0a599c381a85.png)

**Comment by TerrorSquad** [comment]
Did you do a `bin/composer install`?

**Comment by boris1988** [comment]
@TerrorSquad  yep - have got another error.
So decided to install empty version 2.3.3
And one more error. Is this docker-magento useful?
![Screenshot from 2022-04-27 21-16-10](https://user-images.githubusercontent.com/2422927/165593078-92c2e6ce-842e-47d5-85be-e3444d939b76.png)

**Comment by dirkreitz** [comment]
Hi Boris,
we just had this a few days ago. Magento 2.3.3 requires php version 7.3 or lower. Php v 7.3 is EOL, so Mark removed the corresponding php image. If you are stuck to the Magento 2.3.x branch, try 2.3.7.

**Comment by markshust** [comment]
Yes PHP 7.3 is EOL/dead in my head, so no longer supported.

However, 7.3 tags do exist from older versions of docker-magento. You can probably also build your own from the current Docker images, just replacing the 7.4 tag with 7.3. There's nothing wrong with doing this, I'm just not supporting 7.3 out of principle because you should no longer be using it.

You can look up tags at https://hub.docker.com/repository/registry-1.docker.io/markoshust/magento-php/tags?page=1&ordering=last_updated and try to find the corresponding docker-magento version for the related tag.
