### ISSUE TITLE
setup:static-content:deploy takes 15+ minutes on M1 macOS

### ISSUE THREAD

**Issue by Asitis** [markshust/docker-magento#755]
Running the latest Docker setup on a M1 Pro MacBook, everything works fine except running `bin/magento setup:static-content:deploy` takes 15+ minutes every time. Previously, using this Docker setup on Linux it took a minute or 2 tops, same as my other dev servers.

Is this a known bug? Anything to make it faster? I already set RAM and CPU open wide on Docker Desktop, but it's still 15+ minutes. It's kind of stifling my productivity :(

**Comment by rangerz** [comment]
Do you change any setting for `docker-compose.dev.yml` ?

If yes, don't mount `vender` folder

**Comment by Asitis** [comment]
I don't see how that would be the problem, because it's the deployment of the theme that takes forever. Aside that I have always had a few vendor folders mounted, because the modules and themes I develop are based in the vendor folders, and that has never been an issue until I moved to a M1 Mac

**Comment by markshust** [comment]
I'm going to close this one out, because adding vendor changes the performance of this entire project. The directories are very selectively mounted for performance reasons, and changing them around at all sort of voids my "open source warranty" on performance 🤓

You can read more about Docker filesystem performance on Mac's at https://markshust.com/2018/12/30/docker-mac-filesystem-volume-mount-approach-performance/
