### ISSUE TITLE
403 forbidden after new project setup with docker in wsl

### ISSUE THREAD

**Issue by ritzwan0** [markshust/docker-magento#757]
In my WIndows desktop, I am using wsl for Ubuntu. After doing Manual setup with new project using markshust/docker-magento, , I get 403 forbidden error.

**Steps To Reproduce**
Configure wsl in windows
Install Ubuntu 22.04 in windows
Copy markshust/docker-magento.
Following the steps of Manual setup as per "Read Me"
Configure hosts file in Windows (In wsl, type ifconfig command. Copy the ip address of  "eth0" and add it in windows hosts file)
- 172.17.207.62 magento.test

**Expected Result**

Magento homepage of Luma

**Actual Result**

403 Nginx Forbidden error page

**Comment by TheJoelGray** [comment]
I have just completed these instructions and I'm facing the same problem. Is there a workaround or any more information?

**Comment by TheJoelGray** [comment]
As a follow up, I did some more digging and compared between my WSL setup and my Mac setup. 

1. The nginx container is missing the magento config file.
2. For some reason on WSL the `./src/` directory is missing. Looking through the scripts I surmise that it must not be created in the `setup` script but I don't yet know why.
3. I created it and ran the `bin/copyfromcontainer --all` which did populate the directory.
4. I ran `bin/stop` and `bin/start` and viola! Now I have a magento site running!

It does seem as though something else was skipped. Instead of the normal Luna home page I get the admin setup page. I'll try to spend some time next week to see if I can determine what is failing during the process. I imagine there must be an error somewhere that scrolls off the screen and never gets caught.

**Comment by ritzwan0** [comment]
I fixed the prob myself, by adding following line in docker-compose.yml file -

/src/nginx.conf.sample:/var/www/html/nginx.conf:cached

**Comment by uabassguy** [comment]
> As a follow up, I did some more digging and compared between my WSL setup and my Mac setup.
> 
> 1. The nginx container is missing the magento config file.
> 2. For some reason on WSL the `./src/` directory is missing. Looking through the scripts I surmise that it must not be created in the `setup` script but I don't yet know why.
> 3. I created it and ran the `bin/copyfromcontainer --all` which did populate the directory.
> 4. I ran `bin/stop` and `bin/start` and viola! Now I have a magento site running!
> 
> It does seem as though something else was skipped. Instead of the normal Luna home page I get the admin setup page. I'll try to spend some time next week to see if I can determine what is failing during the process. I imagine there must be an error somewhere that scrolls off the screen and never gets caught.

For me it was just running bin/stop and bin/start , for some reason docker-compose up was not doing everything needed to run this

**Comment by markshust** [comment]
I placed a comment to this ticket at https://github.com/markshust/docker-magento/discussions/372, so going to close this one out 👍
