### ISSUE TITLE
Getting error — Project directory is not empty.

### ISSUE THREAD

**Issue by tushar-g** [markshust/docker-magento#805]
**Description**
Magento Version - 2.4.5-p1
I have tried to install using the single command setup on multiple machines (mac, ubuntu) but I keep getting the error:
```
  [InvalidArgumentException]
  Project directory "/var/www/html/." is not empty.
```
This was not the case with version 2.4.5. Tried to google it but not getting any helpful result.

**Steps To Reproduce**
1. Just the run the one line command with version 2.4.5-p1

**Expected Result**
* Magento to be running on local.

**Actual Result**
* Installation errors out. All containers seem to be running 
* State of containers in the attached image:
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/16501551/199169340-daee3c35-58a7-4b1f-a5ab-9e406659da54.png">

**Comment by markshust** [comment]
Everything is working properly, so unable to replicate.

Your error is leading to artifacts being left over from a preexisting install attempt. Please see [markshust/docker-magento#install-fails-because-project-directory-is-not-empty](https://github.com/markshust/docker-magento/#install-fails-because-project-directory-is-not-empty)
