### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by anterpin** [markshust/docker-magento#816]
**Run** `curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/onelinesetup | bas
h -s -- magento.test 2.4.5-p1 community`

**Result**
Composer auth has already been set up.
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Creating a "magento/project-community-edition=2.4.5-p1" project at "./"

                                                     
  [InvalidArgumentException]                         
  Project directory "/var/www/html/." is not empty.  
                                                     

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]

**Comment by denisnaumov22** [comment]
I have the same problem with installing... Can't install new project.

**Comment by scolandrea** [comment]
Check the docker volumes. It seems `appdata` is not empty. You can remove it by using `docker volume rm <volume> -f`

**Comment by baptbzx** [comment]
Is your docker version up to date ?

I've had the same issue and I solved it by updating my docker version from  `20.10.5` to `20.10.20`

**Comment by rangerz** [comment]
run `bin/removeall` and retry again

**Comment by markshust** [comment]
I have no clue why I never created documentation for this. Just added a commit which documents this process:

https://github.com/markshust/docker-magento/#install-fails-because-project-directory-is-not-empty

I'm able to install with no problem at all on Docker `20.10.20`, so going to close this out. But I'm pretty sure what @rangerz suggested and the included documentation as to why this is happening will help you out, if not just let me know.
