### ISSUE TITLE
Link to readme on failed install of project/dir empty

### ISSUE THREAD

**Issue by markshust** [markshust/docker-magento#823]
This error is too prevalent, and is causing too many GitHub issues to be filed:

```
Project directory "/var/www/html/." is not empty error
```

It is also represented by:

```
chmod: cannot access 'bin/magento': No such file or directory
```

What I'd like is that on `bin/start`, detect the presence of either of these errors, then show a message to the user that they have a failed install, and to link to https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty for more information.

**Comment by EvgeniyZverev** [comment]
Hi, @markshust 

I've created a [pull request](https://github.com/markshust/docker-magento/pull/1034) that shows a message to the user that they have a failed install, and to link to https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty for more information.

Could you please review the pull request?

**Comment by markshust** [comment]
Thank you, merged in!
