### ISSUE TITLE
Setup > Manual Setup > Existing Magento Project

### ISSUE THREAD

**Issue by mediawaypoint** [markshust/docker-magento#832]
**Description**

This apparent bug is related to using your docker magento guide on Windows. The specifics of my setup are below:

```
OS: Windows 10
RAM: 32GB (8GB assigned to docker)
WSL version: 2
Distro version: Ubuntu 20.04
```

"There are no commands defined in the app:config namespace."

Course I am doing is: https://courses.m.academy/courses/487758/lectures/9283467

**Steps To Reproduce**
- Rsync existingWebsite datadir
- mysqldump existingWebsite db
- mkdir /home/websupport/Sites
- mkdir /home/websupport/Sites/project
- cd /home/websupport/Sites/project/
- curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash
- cp -R /home/websupport/Sites/existingBlanket/15-12-22/data /home/websupport/Sites/project/src
- bin/start --no-dev
- bin/copytocontainer --all
- bin/mysql < /home/websupport/Sites/existingBlanket/15-12-22/db/15-12-22-blanket.sql
- bin/magento app:config:import

**Expected Result**
Not familiar with this work but I expect it should at least recognise the command I am running.

**Actual Result**
![image](https://user-images.githubusercontent.com/119500023/208438038-7cf5b595-2b03-45fe-9e18-027ec1bb6a23.png)

--------------------------------------------------------------------------------------------------------------------------------------------
**Afterthought / Comments**
To replicate the error, I actually uninstalled docker and all my containers and started from scratch (to ensure I was being as accurate as possible to replicate the issue). Ironically, this seemed to resolve the issue I was getting relating to:

`Error response from daemon: Error porcessing tar file (exist statis 1): cannot overwrite non-directory "/var/www/html/bin" with directory "/var/www/html". `

![Sites-staging_error_copying_to_Container](https://user-images.githubusercontent.com/119500023/208426031-47c57bc5-d7fa-4bd0-8b3d-8c7432adf5cd.jpg)

Note: to retrieve the data directory of the existing website, I ran rsync:
`rsync -azh remoteServer:/var/www/vhosts/website.co.uk/htdocs/ /home/websupport/Sites/existingBlanket/15-12-22/data`

Then I ran the cp -R as per the guide to copy it into the src location as directed.

**Comment by markshust** [comment]
If you uninstall Docker, all of the related Docker volumes are also removed, which means your database was just blown away. Unfortunately I don't support that circumstance -- so don't delete Docker 😄

**Comment by markshust** [comment]
It's not possible to retain an "existing" Magento installation, since Docker stores everything on the Docker filesystem. If you remove Docker, you remove everything that goes with it -- including all files, databases, etc.

You'll need to re-follow the "manual existing setup" instructions to get your site set back up, because once Docker was uninstalled, all of that data was removed with it.

**Comment by danstaver** [comment]
I was trying to install an existing magento project from git, and this was failing for me. I had to add a couple more steps in order to make it work. This is because I was cloning a git repo, which doesnt have some of the folders, like vendor, pub, etc. I was checking what Mark did in his own one line script, and modified the steps in order to account for missing vendor folder and having to run composer install
1. Copy or clone your project to src/ folder
2. Copy a version of app/etc/env.php from one of your environments to src/app/etc/. Update it accordingly to the values from the env/*.env files.
3. Optional: check that you have all the files required in your project. Our git repo was missing some files in app, app/etc (for example NonComposerComponentRegistration.php, db_schema.xml and others...), so i had to manually copy them to /src folder at this point. This is a repo issue, not something with this docker setup, just if someone happen to have the same issue, something to keep in mind. Also, check all the files in compose.dev.yaml which are mounted exist in your project, otherwise you will get an error when trying to start the containers.
4. bin/start --no-dev
5. bin/copytocontainer --all 
At this step, ignore warnings about are some folders missing. When you run bin/copytocontainer --all, it runs bin/fixperms as well. If you check the content of the fixperms, it does this:
bin/clinotty find var vendor pub/static pub/media app/etc \( -type f -or -type d \) -exec chmod u+w {} +;
But, at this point, we do not have these folders in our container yet. I think this script could be optimized, to check first if these folders exists or not.
6. bin/setup-composer-auth
7. bin/clinotty composer config --no-plugins allow-plugins.magento/magento-composer-installer true
bin/clinotty composer config --no-plugins allow-plugins.magento/inventory-composer-installer true
bin/clinotty composer config --no-plugins allow-plugins.laminas/laminas-dependency-plugin true
8. bin/composer install
If vendor folder is not present yet, because we have cloned it from git, run the above command to install all the packages.
9. bin/fixowns && bin/fixperms
10. bin/mysql < your-db-dumb.sql
Import your database and set up any local config values which are specific to your local environment.
11. bin/magento [setup:upgrade](http://setup:upgrade/)
12. bin/clinotty bin/magento [setup:static-content](http://setup:static-content/):deploy -f -j 4
13. bin/clinotty bin/magento [indexer:reindex](http://indexer:reindex/)
14. bin/setup-domain dish-dev.local
15. bin/fixowns && bin/fixperms (idk if this one is required here, i just added it to be sure
16. bin/clinotty bin/magento [cache:flush](http://cache:flush/)
17. bin/clinotty bin/magento [cron:install](http://cron:install/)
18. bin/clinotty bin/magento [deploy:mode](http://deploy:mode/):set developer (probably can skip if you have developer mode in your env.php file already).
And it worked after for me that
