### ISSUE TITLE
/var/www permission denied or  [InvalidArgumentException]   Project directory "/var/www/html/." is not empty.

### ISSUE THREAD

**Issue by skygunner** [markshust/docker-magento#905]
**Description**
New instance Ubuntu 22.04, running the one line installer as normal user. The user has been added to the docker group.

if just go install with the one line installer, it complaints about /var/www/ permission denied while actually there's no /var/www folder. If manually create the folder first and take ownership of the folder, clear the previous oneline installer folder and try again, 
then it complaints about /var/www/html/. is not empty, while actually /var/www is empty? Is this the actual /var/www on the vps or a docker volume somewhere?

```shell
Composer auth has been set up.
Fixing filesystem ownerships...
Filesystem ownerships fixed.
Creating a "magento/project-community-edition=2.4.6" project at "./"


  [InvalidArgumentException]
  Project directory "/var/www/html/." is not empty.
```

**Steps To Reproduce**
if just go install with the one line installer, it complaints about /var/www/ permission denied while actually there's no /var/www folder. If manually create the folder first and take ownership of the folder, clear the previous oneline installer folder and try again, 
then it complaints about /var/www/html/. is not empty, while actually /var/www is empty?

**Comment by MaheshBharadwaj** [comment]
@skygunner how were you able to resolve this issue?

**Comment by haijerome** [comment]
anyone facing this issue just need to remove all the assets, containers along with the volumes associated with them, as described in the documentation below, to get their magento setup completed. I got the same issue after I had resolved some previous conflicts with the setup install.

https://github.com/markshust/docker-magento/#install-fails-because-project-directory-is-not-empty
