### ISSUE TITLE
support for magento 2.4.3-p1

### ISSUE THREAD

**Issue by mahmoud-ismail** [markshust/docker-magento#952]
**Description**
I have an existing project for Magento 2.4.3-p1 with the below prerequisite:

PHP 7.4
Elastic 7.9
Redis 6.x

how can I use or downgrade the current docker-Magento to match that prerequisite.

**Comment by ludcl** [comment]
Hi @mahmoud-ismail, you can [take the version 43.2.0](https://github.com/markshust/docker-magento/releases/tag/43.2.0). Use the content inside "compose" directory and inside "docker-compose.yml" file, replace your PHP image version from `markoshust/magento-php:8.1-fpm-1` to `markoshust/magento-php:7.4-fpm-14`.
You shouldn't have any issue with Elasticsearch 7.16, included in 43.2.0.

**Comment by markshust** [comment]
2.4.3-p1 has been deprecated without updates for almost 2 years now! https://experienceleague.adobe.com/docs/commerce-operations/release/versions.html?lang=en

While I do want to build in the ability to run multiple versions of Magento, they need to be current, active versions of Magento 2. I don't want to support old versions that shouldn't even be used anymore -- it's too much work.

@ludcl has a great tip though that may help you and others out!

**Comment by jasonhildebrand** [comment]
I'll just provide a use case for running outdated versions of Magento.  I'm not saying that docker-magento needs to provide this ability, just saying that it is valid for users to want to do this.

Right now I'm migrating a legacy Magento site (running 2.4.3-p2) to docker-magento.  My approach is to migrate it to docker-magento infrastructure without making any other changes or upgrades, so that I can compare apples to apples and confirm it is working the SAME as the existing site.  Then work on upgrading it to a supported Magento version.

Thank you, @ludcl for these helpful tips.

**Comment by jasonhildebrand** [comment]
These tips helped, but after using them I got a `chmod` error.  I posted the solution here: https://github.com/markshust/docker-magento/issues/769
