### ISSUE TITLE
configuring with varnish.

### ISSUE THREAD

**Issue by zakotajin** [markshust/docker-magento#967]
can someone please give a procedure to configure docker magento with varnish.

Also if someone can help me with installing sample data, FYI `**bin/magneto sampledata:deploy**` this command is giving output that no sample data for these set of modules.

Thanks

**Comment by anvanza** [comment]
Varnish isn't typically installed on a development environment. I would add varnish on a staging/acceptance environment.

Sample data documentation can be found here:
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/next-steps/sample-data/composer-packages.html

**Comment by markshust** [comment]
Yep what @anvanza said, Varnish is very tricky and not recommended to be worked with in a dev environment. If you could convince me otherwise, I may change my mind and support it but I remember the configuration getting extremely large, complex & nasty, and the tradeoffs for implementing this weren't worth the effort and expected use of Varnish for dev.
